// ===== MOCK DATA =====
const PARKINGS = [
  {
    id: 1,
    title: "חניה פרטית מול הים",
    address: "הירקון 80, תל אביב",
    city: "תל אביב",
    type: "פרטית",
    price_hour: 15,
    price_day: 80,
    price_month: 900,
    price_year: 9500,
    rating: 4.9,
    reviews_count: 87,
    emoji: "🌊",
    tags: ["מקורה", "שמירה 24/7", "טעינת חשמל"],
    distance: "200מ׳ מהים",
    lat_pct: 45, lng_pct: 55,
    ev_charger: { type: "AC Type 2", speed_kw: 7, price_per_kwh: 0.85 },
    amenities: ["🔒 שמירה 24/7", "📷 מצלמות", "⚡ טעינת חשמל (7kW)", "♿ נגיש", "🌊 200מ׳ מהים"],
    description: "חניה פרטית מאובטחת ברחוב הירקון, כ-200 מטר מהים. שמירה ומצלמות 24/7. פתיחת שער אוטומטית דרך האפליקציה. מרחק הליכה מהנמל, שוק הכרמל ומרכז תל אביב.",
    host: { name: "דוד כהן", avatar: "#e91e8c", letter: "ד", since: "2023", rating: 4.9, reviews: 134 },
    reviews: [
      { name: "מיכל לב", letter: "מ", color: "#764ba2", date: "מאי 2026", stars: 5, text: "מדהים! הכי קרוב לים שמצאתי. שמירה אמיתית, מצלמות, פתיחת שער חלקה." },
      { name: "יוסי אברהם", letter: "י", color: "#f5576c", date: "אפריל 2026", stars: 5, text: "מחיר מצוין לאזור, ממליץ בחום. הבעלים מגיב מהר לכל שאלה." },
      { name: "שרה גולד", letter: "ש", color: "#4facfe", date: "מרץ 2026", stars: 4, text: "טוב מאוד, אבל הכניסה קצת צרה לרכב גדול. מתאים לרכב בינוני." }
    ]
  },
  {
    id: 2,
    title: "חניה תת-קרקעית מקורה",
    address: "ז׳בוטינסקי 2, רמת גן",
    city: "רמת גן",
    type: "תת-קרקעית",
    price_hour: 12,
    price_day: 65,
    price_month: 750,
    price_year: 8000,
    rating: 4.8,
    reviews_count: 63,
    emoji: "🏢",
    tags: ["מקורה", "מצלמות", "גישה 24/7"],
    distance: "ליד בורסת היהלומים",
    lat_pct: 35, lng_pct: 65,
    amenities: ["🌧️ מקורה", "📷 מצלמות", "🕐 גישה 24/7", "🔒 שמירה"],
    description: "חניה תת-קרקעית מקורה בבניין יוקרתי ברמת גן, צמוד לבורסת היהלומים. גישה 24/7 עם קוד דיגיטלי. מתאים במיוחד לימי גשם.",
    host: { name: "אורה לוי", avatar: "#667eea", letter: "א", since: "2022", rating: 4.8, reviews: 89 },
    reviews: [
      { name: "דן רוזן", letter: "ד", color: "#43e97b", date: "מאי 2026", stars: 5, text: "חניה מושלמת! מקורה, נקייה, ובמחיר מעולה לאזור." },
      { name: "רינה שמיר", letter: "ר", color: "#fa709a", date: "מרץ 2026", stars: 4, text: "טוב מאוד. הגישה קצת מבלבלת בפעם הראשונה אבל אחר כך קל." }
    ]
  },
  {
    id: 3,
    title: "חניה ליד הטיילת",
    address: "הרברט סמואל 40, תל אביב",
    city: "תל אביב",
    type: "חיצונית",
    price_hour: 18,
    price_day: 95,
    price_month: 1100,
    price_year: 11500,
    rating: 4.7,
    reviews_count: 45,
    emoji: "🌅",
    tags: ["שמירה", "מצלמות"],
    distance: "50מ׳ מהטיילת",
    lat_pct: 55, lng_pct: 40,
    amenities: ["📷 מצלמות", "🔒 שמירה", "🏖️ 50מ׳ מהטיילת"],
    description: "חניה פרטית 50 מטר מטיילת תל אביב. נוף לים. שמירה ומצלמות. מתאים מאוד לסופי שבוע ובילויים.",
    host: { name: "יעל גרין", avatar: "#f093fb", letter: "י", since: "2024", rating: 4.7, reviews: 52 },
    reviews: [
      { name: "ניר בן דוד", letter: "נ", color: "#4facfe", date: "מאי 2026", stars: 5, text: "פנינה! בדיוק מול הים, מחיר צודק לאזור. אשתי ואני מזמינים כאן בכל סוף שבוע." }
    ]
  },
  {
    id: 4,
    title: "חניה במגדל יוקרתי",
    address: "אבן גבירול 99, הרצליה",
    city: "הרצליה",
    type: "תת-קרקעית",
    price_hour: 14,
    price_day: 70,
    price_month: 850,
    price_year: 9000,
    rating: 4.9,
    reviews_count: 112,
    emoji: "🏙️",
    tags: ["מקורה", "טעינת חשמל", "נגיש", "גישה 24/7"],
    distance: "מגדלי השרון",
    lat_pct: 25, lng_pct: 70,
    ev_charger: { type: "DC Fast Charge", speed_kw: 22, price_per_kwh: 0.75 },
    amenities: ["⚡ טעינת חשמל (22kW DC)", "♿ נגיש", "🌧️ מקורה", "🕐 24/7", "🔒 שמירה", "📷 מצלמות"],
    description: "חניה בתת-קרקעית של מגדל יוקרתי בהרצליה. עמדת טעינה לרכב חשמלי. שמירה, מצלמות, גישה 24/7. מתאים גם לרכב גדול.",
    host: { name: "שמואל פרידמן", avatar: "#43e97b", letter: "ש", since: "2021", rating: 5.0, reviews: 198 },
    reviews: [
      { name: "אמיר כץ", letter: "א", color: "#e91e8c", date: "מאי 2026", stars: 5, text: "הטובה ביותר שניסיתי. עמדת טעינה חשמלית, ובמחיר הגון!" },
      { name: "לימור מורד", letter: "ל", color: "#764ba2", date: "אפריל 2026", stars: 5, text: "מגיבים מהר, הכל עובד מושלם. אני מחדש בכל חודש." }
    ]
  },
  {
    id: 5,
    title: "חניה במרכז ירושלים",
    address: "ממילא 5, ירושלים",
    city: "ירושלים",
    type: "פרטית",
    price_hour: 10,
    price_day: 55,
    price_month: 650,
    price_year: 7000,
    rating: 4.6,
    reviews_count: 38,
    emoji: "🕌",
    tags: ["מצלמות"],
    distance: "ממילא",
    lat_pct: 70, lng_pct: 50,
    amenities: ["📷 מצלמות", "🕌 ליד העיר העתיקה"],
    description: "חניה פרטית במרכז ירושלים, צמוד לקניון ממילא והעיר העתיקה. מתאים לביקורים, עסקים, ותיירות.",
    host: { name: "משה ברכה", avatar: "#f5576c", letter: "מ", since: "2023", rating: 4.6, reviews: 45 },
    reviews: [
      { name: "תמר גפן", letter: "ת", color: "#667eea", date: "מרץ 2026", stars: 4, text: "מיקום מעולה לירושלים. הכניסה קצת צרה אבל מגיעים בסוף." }
    ]
  },
  {
    id: 6,
    title: "חניה ליד הים — חיפה",
    address: "שדרות בן גוריון 12, חיפה",
    city: "חיפה",
    type: "חיצונית",
    price_hour: 8,
    price_day: 45,
    price_month: 500,
    price_year: 5500,
    rating: 4.5,
    reviews_count: 29,
    emoji: "⚓",
    tags: ["מצלמות"],
    distance: "בת גלים",
    lat_pct: 30, lng_pct: 30,
    amenities: ["📷 מצלמות", "⚓ ליד הים"],
    description: "חניה חיצונית שמשקיפה על הים בחיפה. מחיר שפוי, מיקום טוב לשוק תלפיות ובת גלים.",
    host: { name: "חיים ספיר", avatar: "#4facfe", letter: "ח", since: "2024", rating: 4.5, reviews: 33 },
    reviews: [
      { name: "גלית מור", letter: "ג", color: "#43e97b", date: "מרץ 2026", stars: 4, text: "מחיר מעולה לחיפה. הבעלים נחמד ועוזר." }
    ]
  }
];
